version: "3.7"

services:
  db:
    image: "mysql:8"
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    cap_add:
      - SYS_NICE
